{"links": {"self": {"href": "data/repositories/osrf/cloudsim-legacy/pullrequests/124/comments/419399.json"}, "html": {"href": "#!/osrf/cloudsim-legacy/pull-requests/124/_/diff#comment-419399"}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 124, "links": {"self": {"href": "data/repositories/osrf/cloudsim-legacy/pullrequests/124.json"}, "html": {"href": "#!/osrf/cloudsim-legacy/pull-requests/124"}}, "title": "Making constellations \"cloud agnostic\""}, "content": {"raw": "BTW, there's an ```undefined name``` error in line 646 of ```cloudsimd.py```, not introduced by this branch though, but which prevents ```cloudsimd.py``` from starting the daemon. I fixed the rest of the ```pyflakes``` errors in another branch osrf/cleanup-pyflakes and created a pull request for it to be merged (pull request #125).", "markup": "markdown", "html": "<p>BTW, there's an <code>undefined name</code> error in line 646 of <code>cloudsimd.py</code>, not introduced by this branch though, but which prevents <code>cloudsimd.py</code> from starting the daemon. I fixed the rest of the <code>pyflakes</code> errors in another branch osrf/cleanup-pyflakes and created a pull request for it to be merged (<a href=\"#!/osrf/cloudsim-legacy/pull-requests/125/clean-up-pyflakes-errors\" rel=\"nofollow\" class=\"ap-connect-link\">pull request #125</a>).</p>", "type": "rendered"}, "created_on": "2013-07-29T09:49:07.376979+00:00", "user": {"display_name": "Esteve Fernandez", "uuid": "{b7fa67b3-197b-4687-b526-5583299eb942}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bb7fa67b3-197b-4687-b526-5583299eb942%7D"}, "html": {"href": "https://bitbucket.org/%7Bb7fa67b3-197b-4687-b526-5583299eb942%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/7ed10afdd3c291802b6244f32229c8e1d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsEF-5.png"}}, "nickname": "esteve", "type": "user", "account_id": "557058:58cd8911-f7d9-4a4c-bc21-0f94eb1716d7"}, "updated_on": "2013-07-29T10:01:58.471096+00:00", "type": "pullrequest_comment", "id": 419399}