{"links": {"self": {"href": "data/repositories/osrf/cloudsim-legacy/issues/140/comments/4772987.json"}, "html": {"href": "#!/osrf/cloudsim-legacy/issues/140#comment-4772987"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/cloudsim-legacy/issues/140.json"}}, "type": "issue", "id": 140, "repository": {"links": {"self": {"href": "data/repositories/osrf/cloudsim-legacy.json"}, "html": {"href": "#!/osrf/cloudsim-legacy"}, "avatar": {"href": "data/bytebucket.org/ravatar/{e799e7f6-0caa-464a-97f8-8605a37ebfb1}ts=python"}}, "type": "repository", "name": "cloudsim-legacy", "full_name": "osrf/cloudsim-legacy", "uuid": "{e799e7f6-0caa-464a-97f8-8605a37ebfb1}"}, "title": "Task failed to start then went into starting, then running"}, "content": {"raw": "models are loaded as part of provisioning step", "markup": "markdown", "html": "<p>models are loaded as part of provisioning step</p>", "type": "rendered"}, "created_on": "2013-06-10T22:42:33.654748+00:00", "user": {"display_name": "Hugo Boyer", "uuid": "{3d87874e-7099-4981-b04f-57f0272faa7d}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3d87874e-7099-4981-b04f-57f0272faa7d%7D"}, "html": {"href": "https://bitbucket.org/%7B3d87874e-7099-4981-b04f-57f0272faa7d%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/21198da8539b599e3633017f5f5f8150d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsHB-6.png"}}, "nickname": "hugomatic", "type": "user", "account_id": "557058:869c02bb-b246-4cdc-9db3-0064e8add185"}, "updated_on": null, "type": "issue_comment", "id": 4772987}