{"links": {"self": {"href": "data/repositories/osrf/cloudsim-legacy/issues/126/comments/4279713.json"}, "html": {"href": "#!/osrf/cloudsim-legacy/issues/126#comment-4279713"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/cloudsim-legacy/issues/126.json"}}, "type": "issue", "id": 126, "repository": {"links": {"self": {"href": "data/repositories/osrf/cloudsim-legacy.json"}, "html": {"href": "#!/osrf/cloudsim-legacy"}, "avatar": {"href": "data/bytebucket.org/ravatar/{e799e7f6-0caa-464a-97f8-8605a37ebfb1}ts=python"}}, "type": "repository", "name": "cloudsim-legacy", "full_name": "osrf/cloudsim-legacy", "uuid": "{e799e7f6-0caa-464a-97f8-8605a37ebfb1}"}, "title": "Task does not officially time out"}, "content": {"raw": "Update: I tried with another task, and set the max to 120 sec. At Sim time 112 secs (according to CloudSim), the counter stopped advancing ", "markup": "markdown", "html": "<p>Update: I tried with another task, and set the max to 120 sec. At Sim time 112 secs (according to CloudSim), the counter stopped advancing </p>", "type": "rendered"}, "created_on": "2013-05-31T16:41:09.559781+00:00", "user": {"display_name": "Steffi Paepcke", "uuid": "{88ec2edf-5653-4e93-b139-6f2418d9fde5}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B88ec2edf-5653-4e93-b139-6f2418d9fde5%7D"}, "html": {"href": "https://bitbucket.org/%7B88ec2edf-5653-4e93-b139-6f2418d9fde5%7D/"}, "avatar": {"href": "https://bitbucket.org/account/spaepcke/avatar/"}}, "nickname": "spaepcke", "type": "user", "account_id": null}, "updated_on": null, "type": "issue_comment", "id": 4279713}