{"links": {"self": {"href": "data/repositories/osrf/cloudsim-legacy/issues/49/comments/3310089.json"}, "html": {"href": "#!/osrf/cloudsim-legacy/issues/49#comment-3310089"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/cloudsim-legacy/issues/49.json"}}, "type": "issue", "id": 49, "repository": {"links": {"self": {"href": "data/repositories/osrf/cloudsim-legacy.json"}, "html": {"href": "#!/osrf/cloudsim-legacy"}, "avatar": {"href": "data/bytebucket.org/ravatar/{e799e7f6-0caa-464a-97f8-8605a37ebfb1}ts=python"}}, "type": "repository", "name": "cloudsim-legacy", "full_name": "osrf/cloudsim-legacy", "uuid": "{e799e7f6-0caa-464a-97f8-8605a37ebfb1}"}, "title": "ROS Network is not working properly from the field computer to the local computer"}, "content": {"raw": "We're trying to reproduce the problem here but we don't see the behavior you describe. The only time we observe the error you describe is when the ROS_IP is unset at the moment we start the node (and setting it later does not fix anything). \n\nCan you confirm that the problems persist if you restart your node?\nAlso, can you reproduce the bug using only rostopic pub or is it related to your node?\n\n", "markup": "markdown", "html": "<p>We're trying to reproduce the problem here but we don't see the behavior you describe. The only time we observe the error you describe is when the ROS_IP is unset at the moment we start the node (and setting it later does not fix anything). </p>\n<p>Can you confirm that the problems persist if you restart your node?\nAlso, can you reproduce the bug using only rostopic pub or is it related to your node?</p>", "type": "rendered"}, "created_on": "2013-03-05T00:18:41.636917+00:00", "user": {"display_name": "Hugo Boyer", "uuid": "{3d87874e-7099-4981-b04f-57f0272faa7d}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3d87874e-7099-4981-b04f-57f0272faa7d%7D"}, "html": {"href": "https://bitbucket.org/%7B3d87874e-7099-4981-b04f-57f0272faa7d%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/21198da8539b599e3633017f5f5f8150d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsHB-6.png"}}, "nickname": "hugomatic", "type": "user", "account_id": "557058:869c02bb-b246-4cdc-9db3-0064e8add185"}, "updated_on": null, "type": "issue_comment", "id": 3310089}