{"changes": {"state": {"new": "resolved", "old": "new"}}, "links": {"self": {"href": "data/repositories/osrf/cloudsim-legacy/issues/135/changes/4746572.json"}, "html": {"href": "#!/osrf/cloudsim-legacy/issues/135#comment-4746572"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/cloudsim-legacy/issues/135.json"}}, "type": "issue", "id": 135, "repository": {"links": {"self": {"href": "data/repositories/osrf/cloudsim-legacy.json"}, "html": {"href": "#!/osrf/cloudsim-legacy"}, "avatar": {"href": "data/bytebucket.org/ravatar/{e799e7f6-0caa-464a-97f8-8605a37ebfb1}ts=python"}}, "type": "repository", "name": "cloudsim-legacy", "full_name": "osrf/cloudsim-legacy", "uuid": "{e799e7f6-0caa-464a-97f8-8605a37ebfb1}"}, "title": "Explicit load of ixgbe module needs to escape call to `uname`"}, "created_on": "2013-06-08T01:32:05.958792+00:00", "user": {"display_name": "Carlos Ag\u00fcero", "uuid": "{da8a8e89-4bb0-421b-bd0e-dbbed3d4ed6a}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bda8a8e89-4bb0-421b-bd0e-dbbed3d4ed6a%7D"}, "html": {"href": "https://bitbucket.org/%7Bda8a8e89-4bb0-421b-bd0e-dbbed3d4ed6a%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/692bf15758111acaddae4da15a47f9e5d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsCA-0.png"}}, "nickname": "caguero", "type": "user", "account_id": "557058:4ded1ddf-947e-4154-bbd1-3dba24f1bdbd"}, "message": {"raw": "Fixed in pull request [135](#!/osrf/cloudsim/pull-request/98/fix-issue-135-escape-back-quotes/)", "markup": "markdown", "html": "<p>Fixed in pull request <a data-is-external-link=\"true\" href=\"#!/osrf/cloudsim/pull-request/98/fix-issue-135-escape-back-quotes/\" rel=\"nofollow\">135</a></p>", "type": "rendered"}, "type": "issue_change", "id": 4746572}