{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/cloudsim-legacy.json"}, "html": {"href": "#!/osrf/cloudsim-legacy"}, "avatar": {"href": "data/bytebucket.org/ravatar/{e799e7f6-0caa-464a-97f8-8605a37ebfb1}ts=python"}}, "type": "repository", "name": "cloudsim-legacy", "full_name": "osrf/cloudsim-legacy", "uuid": "{e799e7f6-0caa-464a-97f8-8605a37ebfb1}"}, "links": {"attachments": {"href": "data/repositories/osrf/cloudsim-legacy/issues/122/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/cloudsim-legacy/issues/122.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/cloudsim-legacy/issues/122/watch"}, "comments": {"href": "data/repositories/osrf/cloudsim-legacy/issues/122/comments_page=1.json"}, "html": {"href": "#!/osrf/cloudsim-legacy/issues/122/deleting-a-task-while-stopping-causes"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/cloudsim-legacy/issues/122/vote"}}, "reporter": {"display_name": "Brian Gerkey", "uuid": "{3d8b5763-9dad-4be7-85c2-a7ab6cd49173}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D"}, "html": {"href": "https://bitbucket.org/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:2e35028e-9ad8-4d6a-a3a5-275159a304a9/5fa9ec73-0fec-4860-a202-e34ae23b6a12/128"}}, "nickname": "Brian Gerkey", "type": "user", "account_id": "557058:2e35028e-9ad8-4d6a-a3a5-275159a304a9"}, "title": "Deleting a task while stopping causes inconsistent state", "component": null, "votes": 0, "watches": 0, "content": {"raw": "A team got their CloudSim into a state where no new tasks could be started.  On inspection of the redis database, `current_task` was set to a task ID that did not appear in the `tasks` list.  Logs demonstrate that the following sequence occurred:\r\n\r\n* create task command issued\r\n* task state: ready\r\n* start task command issued\r\n* task state: starting\r\n* task state: running\r\n* 17 hours elapsed\r\n* stop task command issued\r\n* task state: stopping\r\n* delete task command issued, causing task to be removed from the `tasks` list\r\n* task state: stopped\r\n\r\nCleanup in the last step failed because the task had already been removed from the list.  The delete button is/should be disabled in the web UI after issued the stop command, but the delete command is not locked out in the backend, so a second / stale web browser could have allowed the delete command to be issued.\r\n\r\n", "markup": "markdown", "html": "<p>A team got their CloudSim into a state where no new tasks could be started.  On inspection of the redis database, <code>current_task</code> was set to a task ID that did not appear in the <code>tasks</code> list.  Logs demonstrate that the following sequence occurred:</p>\n<ul>\n<li>create task command issued</li>\n<li>task state: ready</li>\n<li>start task command issued</li>\n<li>task state: starting</li>\n<li>task state: running</li>\n<li>17 hours elapsed</li>\n<li>stop task command issued</li>\n<li>task state: stopping</li>\n<li>delete task command issued, causing task to be removed from the <code>tasks</code> list</li>\n<li>task state: stopped</li>\n</ul>\n<p>Cleanup in the last step failed because the task had already been removed from the list.  The delete button is/should be disabled in the web UI after issued the stop command, but the delete command is not locked out in the backend, so a second / stale web browser could have allowed the delete command to be issued.</p>", "type": "rendered"}, "assignee": null, "state": "resolved", "version": null, "edited_on": null, "created_on": "2013-05-29T21:48:33.288093+00:00", "milestone": null, "updated_on": "2013-05-29T22:26:44.113069+00:00", "type": "issue", "id": 122}