{"priority": "blocker", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/cloudsim-legacy.json"}, "html": {"href": "#!/osrf/cloudsim-legacy"}, "avatar": {"href": "data/bytebucket.org/ravatar/{e799e7f6-0caa-464a-97f8-8605a37ebfb1}ts=python"}}, "type": "repository", "name": "cloudsim-legacy", "full_name": "osrf/cloudsim-legacy", "uuid": "{e799e7f6-0caa-464a-97f8-8605a37ebfb1}"}, "links": {"attachments": {"href": "data/repositories/osrf/cloudsim-legacy/issues/6/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/cloudsim-legacy/issues/6.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/cloudsim-legacy/issues/6/watch"}, "comments": {"href": "data/repositories/osrf/cloudsim-legacy/issues/6/comments_page=1.json"}, "html": {"href": "#!/osrf/cloudsim-legacy/issues/6/the-security-group-teamlogin-does-not"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/cloudsim-legacy/issues/6/vote"}}, "reporter": {"display_name": "Hugo Boyer", "uuid": "{3d87874e-7099-4981-b04f-57f0272faa7d}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3d87874e-7099-4981-b04f-57f0272faa7d%7D"}, "html": {"href": "https://bitbucket.org/%7B3d87874e-7099-4981-b04f-57f0272faa7d%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/21198da8539b599e3633017f5f5f8150d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsHB-6.png"}}, "nickname": "hugomatic", "type": "user", "account_id": "557058:869c02bb-b246-4cdc-9db3-0064e8add185"}, "title": "The security group 'teamlogin' does not exist", "component": null, "votes": 0, "watches": 1, "content": {"raw": "The security group 'teamlogin' does not exist. Note in the post below, I removed my email, key and secret_key. How can I resolve this? Thanks.\r\n\r\nmighty@itauma:~/Projects/cloudsim-1.0.0$ ./bin/create_cloudsim.py myemail@gmail.com mykey mysecret_key\r\n./inside/cgi-bin\r\n./cloudsimd/launchers\r\n./cloudsimd/launchers/cloudsim.pyc\r\nWarning: redis not installed.\r\ncloudsim log> cloudsim launch constellation 'b592a288-4298-11e2-b2c3-0025d3644a10'\r\nevent: cloudsim\r\ndata:{'state': 'reserve', 'machine_name': 'cloudsim_b592a288-4298-11e2-b2c3-0025d3644a10', 'type:': 'launch'}\r\n\r\n\r\nTraceback (most recent call last):\r\n  File \"./bin/create_cloudsim.py\", line 51, in <module>\r\n    machine = cloudsim.cloudsim_bootstrap(username, tmp_fname.name)\r\n  File \"./cloudsimd/launchers/cloudsim.py\", line 223, in cloudsim_bootstrap\r\n  File \"./cloudsimd/launchers/cloudsim.py\", line 133, in launch\r\n  File \"./inside/cgi-bin/common/machine.py\", line 124, in __init__\r\n  File \"./inside/cgi-bin/common/machine.py\", line 170, in _launch\r\n  File \"/usr/lib/python2.7/dist-packages/boto/ec2/connection.py\", line 670, in run_instances\r\n    return self.get_object('RunInstances', params, Reservation, verb='POST')\r\n  File \"/usr/lib/python2.7/dist-packages/boto/connection.py\", line 916, in get_object\r\n    raise self.ResponseError(response.status, response.reason, body)\r\nboto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request\r\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n<Response><Errors><Error><Code>InvalidGroup.NotFound</Code><Message>The security group 'teamlogin' does not exist</Message></Error></Errors><RequestID>b32b9e4b-7934-486e-bd9d-e085eb5c2636</RequestID></Response>", "markup": "markdown", "html": "<p>The security group 'teamlogin' does not exist. Note in the post below, I removed my email, key and secret_key. How can I resolve this? Thanks.</p>\n<p>mighty@itauma:~/Projects/cloudsim-1.0.0$ ./bin/create_cloudsim.py myemail@gmail.com mykey mysecret_key\n./inside/cgi-bin\n./cloudsimd/launchers\n./cloudsimd/launchers/cloudsim.pyc\nWarning: redis not installed.\ncloudsim log&gt; cloudsim launch constellation '<a href=\"#!/osrf/cloudsim-legacy/commits/b592a288\" rel=\"nofollow\" class=\"ap-connect-link\">b592a288</a>-4298-11e2-b2c3-0025d3644a10'\nevent: cloudsim\ndata:{'state': 'reserve', 'machine_name': 'cloudsim_b592a288-4298-11e2-b2c3-0025d3644a10', 'type:': 'launch'}</p>\n<p>Traceback (most recent call last):\n  File \"./bin/create_cloudsim.py\", line 51, in &lt;module&gt;\n    machine = cloudsim.cloudsim_bootstrap(username, tmp_fname.name)\n  File \"./cloudsimd/launchers/cloudsim.py\", line 223, in cloudsim_bootstrap\n  File \"./cloudsimd/launchers/cloudsim.py\", line 133, in launch\n  File \"./inside/cgi-bin/common/machine.py\", line 124, in <strong>init</strong>\n  File \"./inside/cgi-bin/common/machine.py\", line 170, in _launch\n  File \"/usr/lib/python2.7/dist-packages/boto/ec2/connection.py\", line 670, in run_instances\n    return self.get_object('RunInstances', params, Reservation, verb='POST')\n  File \"/usr/lib/python2.7/dist-packages/boto/connection.py\", line 916, in get_object\n    raise self.ResponseError(response.status, response.reason, body)\nboto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request\n&lt;?xml version=\"1.0\" encoding=\"UTF-8\"?&gt;\n&lt;Response&gt;&lt;Errors&gt;&lt;Error&gt;&lt;Code&gt;InvalidGroup.NotFound&lt;/Code&gt;&lt;Message&gt;The security group 'teamlogin' does not exist&lt;/Message&gt;&lt;/Error&gt;&lt;/Errors&gt;&lt;RequestID&gt;<a href=\"#!/osrf/cloudsim-legacy/commits/b32b9e4b\" rel=\"nofollow\" class=\"ap-connect-link\">b32b9e4b</a>-7934-486e-bd9d-e085eb5c2636&lt;/RequestID&gt;&lt;/Response&gt;</p>", "type": "rendered"}, "assignee": {"display_name": "Hugo Boyer", "uuid": "{3d87874e-7099-4981-b04f-57f0272faa7d}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3d87874e-7099-4981-b04f-57f0272faa7d%7D"}, "html": {"href": "https://bitbucket.org/%7B3d87874e-7099-4981-b04f-57f0272faa7d%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/21198da8539b599e3633017f5f5f8150d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsHB-6.png"}}, "nickname": "hugomatic", "type": "user", "account_id": "557058:869c02bb-b246-4cdc-9db3-0064e8add185"}, "state": "resolved", "version": null, "edited_on": null, "created_on": "2012-12-10T18:11:21.617215+00:00", "milestone": null, "updated_on": "2012-12-11T02:49:50.623821+00:00", "type": "issue", "id": 6}